### ISSUE TITLE
Make it easy to get a good first impression

### ISSUE THREAD

**Issue by MarcSkovMadsen** [fstroth/icevision_dashboards#11]
Hi

I am a contributor to Panel. I was trying to find out what this project is and how it uses Panel.

What would help me is 1) Some kind of text introduction describing the why and what 2) a link to binder to make it easy to try out.

```markdown
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/fstroth/icevision_dashboards/HEAD)
```

**Comment by fstroth** [comment]
Hey @MarcSkovMadsen,

thank you for the issue. Yeah, I have been neglecting that part quite a bit! I will add Binder and an introductory text. Any questions about the lib or feedback on how Panel is used is very welcome.
