### ISSUE TITLE
Upgrade `icevision` to 0.12.0

### ISSUE THREAD

**Issue by strickvl** [fstroth/icevision_dashboards#18]
Are you anticipating that you'll upgrade the icevision dependency to 0.12.0? It's on 0.11 at the moment, I think.

**Comment by fstroth** [comment]
Yes, will check against the newest version, fix all problems and then update.
Should be some time next week.

**Comment by strickvl** [comment]
Thanks!

**Comment by fstroth** [comment]
Done, the new release is up: https://pypi.org/project/icevision-dashboards/0.0.8/

**Comment by strickvl** [comment]
Thank you!
